### ISSUE TITLE
Where can I find the Advanced F3 mod like in this video?

### ISSUE THREAD

**Issue by kleinermob** [FrederoxDev/Amethyst#111]
https://youtu.be/5yaLlH_SbB8?t=261

**Comment by CreeperG16** [comment]
I don't think it's been released yet
or even finished for that matter
but idk

**Comment by Adrian8115** [comment]
Yeah, that's my mod.. you can find the repo here: https://github.com/Adrian8115/AdvancedF3
It is **not** released yet
