### ISSUE TITLE
it deletes my minecraft

### ISSUE THREAD

**Issue by YaghoobMB** [FrederoxDev/Amethyst#118]
every time i press lunch game button , the original game will be disappear from my pc and i have to install Minecraft again.

**Comment by FrederoxDev** [comment]
what version of the runtime are you using?

**Comment by YaghoobMB** [comment]
2.5.3

**Comment by FrederoxDev** [comment]
and installing through the launcher isn't working? are you getting errors, can you launch via the launcher?

**Comment by YaghoobMB** [comment]
at first it says "the target version is not downloaded" and download starts.
after download is completed , this will happen and then it says "no app can run the link" or something like that and Microsoft store lunches to find an app.
I'm not sure you understand me but I'm trying my best . I'm just an English learner

**Comment by OmniacDev** [comment]
Thanks for the info, could you open the Developer Console using `Ctrl + Shift + i` and tell me what it says in there after all this happens?

Also, this issue should be moved over [here](https://github.com/FrederoxDev/Amethyst-Launcher/issues/52).
