### ISSUE TITLE
Build with Debug with /MDd flag

### ISSUE THREAD

**Issue by FrederoxDev** [FrederoxDev/Amethyst#19]
Look into the possibility of allowing building with debug for speed with the /MDd flag

**Comment by FrederoxDev** [comment]
- seems to have issues with EnTT, static assertions failed for sizes when in debug with this flag

**Comment by Duckos-Mods** [comment]
To do this i would. Disable optimizations. Then link with release libraries. That tends to work. I did that when working with LeviLama

**Comment by FrederoxDev** [comment]
EnTT is a header only library so i'm not sure if I can just build it to a library?

**Comment by DisabledMallis** [comment]
On my fork on the amethyst-api branch I have been able to get this to build with the Debug configuration, havent tested yet though. Still used the `_ITERATOR_DEBUG_LEVEL` but its in combination with Brady's advice of using `MSVC_RUNTIME_LIBRARY` on #35

**Comment by ZeroMemes** [comment]
Conditionally using MultiThreaded (/MT) in release mode and MultiThreadedDLL (/MD) in debug mode is probably the way to go for improved debug mode compiled times.

Using either version of the debug standard library shouldn’t be considered because of allocator mismatch.
