### ISSUE TITLE
Launch Minecraft suspended

### ISSUE THREAD

**Issue by FrederoxDev** [FrederoxDev/Amethyst#32]
The project long-term needs to be able to hook functions which are called really early. This would be a significant thing for the project, and would solve one of the problems with the api running before it's possible to attach a debugger

**Comment by DisabledMallis** [comment]
Why not do what MCLauncher or Jiayi does, and download a seperate instance of the game somewhere else? Then you can create some kind of proxy launcher dll [like I did on my NKHook project](https://github.com/NKHook/NKHook5/blob/master/Loader/main.cpp) which allows me to run code right before the game starts running, but after its loaded into memory. This way you can apply your patches, scan all of the sigs, and much more before the game even does anything.

**Comment by Duckos-Mods** [comment]
> Why not do what MCLauncher or Jiayi does, and download a seperate instance of the game somewhere else? Then you can create some kind of proxy launcher dll [like I did on my NKHook project](https://github.com/NKHook/NKHook5/blob/master/Loader/main.cpp) which allows me to run code right before the game starts running, but after its loaded into memory. This way you can apply your patches, scan all of the sigs, and much more before the game even does anything.

For doing that. Wouldnt we need to find a dll the game calls to and doesnt import like 600 functions? Or would it make more sense to just auto generate most the the function from an import table and just add our own data onto it

**Comment by DisabledMallis** [comment]
Yea we would, but I'm sure we could pick a decent candidate.

**Comment by Duckos-Mods** [comment]
I have implemented this via a proxy dll which spoofs being a required dll by the game. Only thing i havent done is make the launcher copy the proxy into the games install dir, and or download the required mc version which i plan to do
