### ISSUE TITLE
Better CMake build setup

### ISSUE THREAD

**Issue by DisabledMallis** [FrederoxDev/Amethyst#34]
It is typical for CMake projects to have a single main CMakeLists.txt file that is used to build the whole project. It would be reasonable to leave the other CMakeLists files as their own projects as well, like in the AmethingRuntime and AmethystAPI folders so they can be built independently as their own project as well.

On top of this, libraries should be submodules and not .lib files with the headers in the project files directly. The benefit of submodules like this is that they can be built independently, and linked with the project in the same way, but a .lib and header files do not need to be committed to the repository. I find it to be generally bad practice to have pre-built libraries included in the source code of projects.

I'm going to start working on this on my fork and will submit a pull request hopefully changing this about the project.

**Comment by FrederoxDev** [comment]
Ah yeah having one CMakelists at the root is fine, as long as they can still be built individually. 

I've been meaning to move to another thing like submodules, I specifically myself was looking into using fetch content in cmake? Sounds good!

**Comment by DisabledMallis** [comment]
Yea I usually use fetch content, but the problem is that it fetches it individually for each build configuration. I usually use this is my own projects, and I can set it up here too if you'd like that instead.

**Comment by FrederoxDev** [comment]
Either is fine
