### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by EnderBoy2000** [FrederoxDev/Amethyst#5]
This is not an issue but my only way i found to contact i just want to ask if and where there are any mods and/or installation guides for amethyst launcher

**Comment by FrederoxDev** [comment]
Hey, so far there's one released mod called ItemInformation which adds more info to items on hover.

There is a basic setup guide for amethyst in the project server https://discord.gg/Cxrj9UXnDB 

Happy to answer any questions in the server too!
