### ISSUE TITLE
Documentation please

### ISSUE THREAD

**Issue by RevisedJDUDE2** [FrederoxDev/Amethyst#52]
Please make an documentation so I can see what I can do... Like functions and classes.

Sorry for making an issue

**Comment by ATXLtheAxolotl** [comment]
You can check this but it isn’t that developed at the moment. You can find most of our classes and implementations through the source code.

Please keep in mind this is not a beginner level project and we are limited by what we can reverse engineer.

**Comment by FrederoxDev** [comment]
> Please make an documentation so I can see what I can do... Like functions and classes.
> 
> Sorry for making an issue

Are you referring to documentation for Amethyst's stuff? If so I agree, but its not really a priority for myself.

If you mean documentation for bedrocks stuff, that's not really realistic for the project at the moment

**Comment by Adrian8115** [comment]
How about a community maintained documentation?

**Comment by Adrian8115** [comment]
Maybe something with mkdocs.. idk
Could be extremly helpful for new people or people seeking to understand amethyst better

**Comment by FrederoxDev** [comment]
There's definitely a large difference between asking for docs for amethyst and Minecraft itself.

I completely agree that amethyst itself needs docs, but not Minecraft itself at this point

https://frederoxdev.github.io/Bedrock-Modding-Guide/1.1_Install_Amethyst

I also want to keep adding to help share knowledge

**Comment by Adrian8115** [comment]
Yeah understandable...
But documenting some of Minecrafts Internals could be helpful to other mibecraft modding communities.. the question is will mojang do something against it?

But wiki/documentation is definitly needed for anethyst, how to use/instal it and how to make plugins..
The best would be if it all was in a central amethyst wiki/docs

**Comment by FrederoxDev** [comment]
What we are doing is completely fine, as we aren't:
 shipping the game itself
 shipping the games source code 

Everything we have is community reversed.
