### ISSUE TITLE
Bug: afterTick/beforeTick is called too often

### ISSUE THREAD

**Issue by Adrian8115** [FrederoxDev/Amethyst#53]
This is my example code:
```c++
#include <chrono>

std::chrono::time_point<std::chrono::system_clock> last;

ModFunction void Initialize(HookManager* hookManager, Amethyst::EventManager* eventManager, InputManager* inputManager)
{
    eventManager->afterTick.AddListener(afterTick);
}

void afterTick(){
    std::chrono::time_point<std::chrono::system_clock> now = std::chrono::system_clock::now();
    auto duration = now - last;

    // millis since last tick (for 20 ticks per sec ~ 50ms difference)
    auto millis = std::chrono::duration_cast<std::chrono::milliseconds>(duration).count();

    Log::Info("MILLS SINCE LAST TICK: {}", millis);

    last = std::chrono::system_clock::now();
}
```
This code gives me 16/17ms per tick, which roughly means it is executed 60 times per second,
but there are normally just 20 ticks in a second

Using beforeTick doesn't really change anything.

It seems like it uses the wrong function for ticking

**Comment by FrederoxDev** [comment]
By the fact that this is called every 16ms, that definitely would line up to be called every frame running at 60 fps (1/60s = 16.3ms) 

Which makes sense as we've hooked Minecraft::update rather then a tick function

**Comment by Adrian8115** [comment]
that's what I thought

**Comment by Adrian8115** [comment]
It would be good to have the Minecraft::update function still around, just nder another name...

**Comment by FrederoxDev** [comment]
https://github.com/FrederoxDev/Amethyst/commit/9482827644cd3155fdcc3c31ecdf078ffb96983d

Renamed to be more accurate here

**Comment by Adrian8115** [comment]
we'll get the tick func beack one day, right?
