### ISSUE TITLE
Feature Request: onStartCloseGame

### ISSUE THREAD

**Issue by Adrian8115** [FrederoxDev/Amethyst#54]
We have `onStartJoinGame`, which allows use to run code when a player joins a world.
If we want to stop something when the player closes a world, we don't have anything...

That's why I propose to have a `onStartCloseGame` func,
which will allow us to execute code when a world is closed

This will help prevent crahes when a world is closed, but the mod still thinks the player is in the world

**Comment by FrederoxDev** [comment]
I'll have this added for 1.2.0, there's just a func for this in ClientInstance IIRC

**Comment by FrederoxDev** [comment]
https://github.com/FrederoxDev/Amethyst/commit/9482827644cd3155fdcc3c31ecdf078ffb96983d

Now added as an event onRequestLeaveGame
