### ISSUE TITLE
Feature Request: blocksource* in CI headers

### ISSUE THREAD

**Issue by Adrian8115** [FrederoxDev/Amethyst#55]
As I was told CI has a blocksource*, but we don't have it in the headers rn

Would be nice to add it...

It would give access to mods to get blockpos and other instances which could be used with getMapColor or other funcs to interact with the current level/world

**Comment by Adrian8115** [comment]
Will we get this in 1.2.0?

**Comment by FrederoxDev** [comment]
Yeah

**Comment by FrederoxDev** [comment]
Done 👍 Should be good, although I haven't got a way to test it
