### ISSUE TITLE
Feature Request: in code construction of TexturePtr

### ISSUE THREAD

**Issue by Adrian8115** [FrederoxDev/Amethyst#56]
We can get TexturePtr by loading it from the ResourceLocation
but we curreently can't construct it in code...

It would be absolutly useful to make it code generatable.
We could draw procedural textures and would not need to use drawRect with many small rectangle blobs
This would also allow us to not render these every frame, instead just build them every few second or so
and then just to use them every frame.

I've looked into this but couldn't find anything useful...

**Comment by FrederoxDev** [comment]
After thinking about it I think our best approach is to re-impl drawing textures on screen

**Comment by Adrian8115** [comment]
What did you think off?
How should it be reimpl and what should we make better?

**Comment by FrederoxDev** [comment]
I'm making a few assumptions that drawImage is actually in charge of drawing a texture, we could just re-impl what it does but instead replace it pulling the texture from a TexturePtr to where-ever we want

**Comment by FloppyDolphin57** [comment]
> I'm making a few assumptions that drawImage is actually in charge of drawing a texture, we could just re-impl what it does but instead replace it pulling the texture from a TexturePtr to where-ever we want

Not so simple, the way textures are stored is aids. I'd suggest you try to construct a BedrockTexture using a cg::Image and then taking the shared BedrockTextureData inside of it and putting it into a TexturePtr
