### ISSUE TITLE
Partial Support for latest

### ISSUE THREAD

**Issue by FrederoxDev** [FrederoxDev/Amethyst#61]
It could be nice to have support for the latest version of the game, with minimal features enabled etc (e.g. no input handling etc), while also not moving amethyst entirely to a version.

That way some mods that are smaller in size can be updated to trail latest stable release. I'm not entirely sure how this will be able to be managed on git, we can make a fork and make changes to that branch etc, but im not sure if we can properly keep that branch updated from main?

As of current I want to keep working on 1.20.51 until I have gotten most of the stuff I want to explore and do in amethyst

**Comment by Adrian8115** [comment]
Well, this gives us the question again, is it worth it?

Afaik there are no mods that might use this..
So idk if we really need it ~ we might still be better off expanding 1.20.51.1
