### ISSUE TITLE
Hot reloading is broken

### ISSUE THREAD

**Issue by FrederoxDev** [FrederoxDev/Amethyst#69]
its been broken for a little while. will look into it soon.

**Comment by Adrian8115** [comment]
I think it is fixed now..

**Comment by Adrian8115** [comment]
Hold up NOT FIXED

**Comment by FrederoxDev** [comment]
Can you be more specific, this should've been fixed in one of the commits recently.

**Comment by Adrian8115** [comment]
https://github.com/FrederoxDev/Amethyst/assets/127942625/37cd498e-5194-48e4-acaf-346918b3d804

I'm on `1.20.72` and ui rendering breaks with every hot reload

**Comment by Adrian8115** [comment]
same with `1.20.71`

**Comment by FrederoxDev** [comment]
![image](https://github.com/FrederoxDev/Amethyst/assets/69014593/445e11e3-c40d-45b6-8899-2b2da02811c4)

I've also been noticing occasional infinite loops, they arent consistent though

**Comment by Adrian8115** [comment]
I haven't experienced that

**Comment by FrederoxDev** [comment]
![image](https://github.com/FrederoxDev/Amethyst/assets/69014593/87921bb7-502e-4b3e-bb7a-ffbba8e3bfac)

Ok yeah I am experiencing the same problem you had, events aren't getting after hot reloading..

**Comment by FrederoxDev** [comment]
Closing for now, lemme know if you run into any more problems.

**Comment by Adrian8115** [comment]
thx
