### ISSUE TITLE
Re-Implement the input system

### ISSUE THREAD

**Issue by FrederoxDev** [FrederoxDev/Amethyst#71]
I have a few paths I potentially want to take the input system, the first is finding a way to listen to key presses directly, although this comes at the trade off of not being rebind-able through the game which is important to me.

The second option is to try and track down where the vector of key-mappings gets stored in the game, so that we can modify it while running, rather than having to rely on the game calling it. My issue with the old input system, was that it was a bit too sketchy, with large chunks of it not working with hot reloading

**Comment by Adrian8115** [comment]
most of it is now done.
The only thing that should still be done is moving the registering of event handlers into its own event

**Comment by FrederoxDev** [comment]
Can you make a new issue for this? This one probably should've been closed as I did what I wanted for this
