### ISSUE TITLE
Auto-Generated Documentation

### ISSUE THREAD

**Issue by FrederoxDev** [FrederoxDev/Amethyst#72]
Does anyone have any experience with auto generated c++ documentation? It could be nice to get some basic stuff up, things I'm looking for:

- being able to stick examples in doc comments, I've seen this in visual studio code with some npm libraries. I'm assuming this is possible with visual studio?

- build to a static site (nice to have, not necessary)

**Comment by Adrian8115** [comment]
I used MkDocs for my docs all the time... a simple example: https://adrian8115.github.io/RAstra/

But it sadly doesn't have the ability for custom code docs, we would need to use something like DoxyGen, DoxyPress or DocFx

We could even use tech like DoxyGen and MkDocs together for the best experience.
MkDocs would even allow us to document multiple different version of our software

**Comment by Adrian8115** [comment]
this is wip rn and on the org:
https://github.com/AmethystAPI/Amethyst-Docs

**Comment by Tallis-Larsen** [comment]
im not meant to see the \docs directory in my amethyst clone, correct? that's still WIP or am i missing something?

**Comment by Adrian8115** [comment]
No you should not see that afaik

**Comment by Adrian8115** [comment]
yep this not useful
