### ISSUE TITLE
Proposition: Compile server side mods

### ISSUE THREAD

**Issue by FrederoxDev** [FrederoxDev/Amethyst#79]
It could be interesting to allow users to easily make server side mods in the same source as their client side mods, since I am moving the project in the direction of autogenerated headers, we could switch addresses to be got externally when targeting server.

I'm not too sure on the specifics on the idea though, the goal of the project still is client stuff, but having the ability to do both would be powerful

**Comment by Adrian8115** [comment]
I would say we could certainly do this one day... but we should focus on client side stuff for now

**Comment by Duckos-Mods** [comment]
If this is something that you are interested in. I know some people who might be willing to help with the server end of Amethyst.
