### ISSUE TITLE
Near-Term Roadmap

### ISSUE THREAD

**Issue by FrederoxDev** [FrederoxDev/Amethyst#81]
My near term goals for the amethyst project is to overhall mod management within Amethyst Launcher

- Versions of runtime should be available to be downloaded through amethyst launcher
- We need a better way of updating the launcher, it should be able to fetch its own updates to avoid users having to manually update it each time
- We need a better mod management system. Drag to import, UI to manage things with mods, e.g. remove them

**Comment by Xterionix** [comment]
Bridge v1 supports fetching its updates if you're looking for somewhere to start on that

**Comment by Adrian8115** [comment]
Another important thing is loading mods from zip archives... or even using a custom file extension

**Comment by FrederoxDev** [comment]
That's what I mean by drag to import, also thoughts on using `.ame`?

**Comment by Adrian8115** [comment]
`.ame` sounds and looks really weird, Id propose `.mcmod`

**Comment by Tallis-Larsen** [comment]
I do like that `.mcmod` stays consistent with the current MC file extensions. https://learn.microsoft.com/en-us/minecraft/creator/documents/minecraftfileextensions?view=minecraft-bedrock-stable

**Comment by Adrian8115** [comment]
That was a intention of mine, but on the other hand it is still unofficial.. and maybe too much of an umberella term.
I'd say we should document the format well enough for other mod loaders to use it.

**Comment by jLn0n** [comment]
perhaps `.mcamod`

**Comment by OmniacDEV** [comment]
`.meth`

**Comment by FrederoxDev** [comment]
All of these suggestions have been implemented, unsure why this issue was made on the main repo
