### ISSUE TITLE
Fuck Microsoft

### ISSUE THREAD

**Issue by Timbo303** [FrederoxDev/Amethyst#89]
They hate us that's for certain. They need to revert this asap.

https://media.discordapp.net/attachments/669004416220921861/1247991860354613340/image.png?ex=6662b33e&is=666161be&hm=081736922cd8b9fa4d64d7cadc8e973d36c647b340faa8bb1ed06e8ff52f1f8f&=&format=webp&quality=lossless&width=1378&height=295

**Comment by Adrian8115** [comment]
but why are you creating an issue for this on the amethyst github?
