### ISSUE TITLE
wait is this for mobile...

### ISSUE THREAD

**Issue by Celestemysterios** [FrederoxDev/Amethyst#92]
i cant see an apk anywhere...

**Comment by FrederoxDev** [comment]
Not for mobile as of right now. Only windows 10

**Comment by Celestemysterios** [comment]
sad

**Comment by Celestemysterios** [comment]
> Not for mobile as of right now. Only windows 10

is there any plans for adding support to mobile anytime soon? /crs

**Comment by FrederoxDev** [comment]
Not anytime soon, maybe long term if we do end up being stuck on this version forever.

**Comment by joeyoropesa-dev** [comment]
> Not anytime soon, maybe long term if we do end up being stuck on this version forever.

Well could we at least get a list of C++ modloaders for Minecraft Bedrock on Android (if any)

**Comment by KoshakMineDEV** [comment]
Horizon(Inner Core 2.0), with support of C++, Java and JS modding for android. but it's 1.16.201 and closed source. We migrated to armv8(arm64) version of the game from armv7 recently

**Comment by joeyoropesa-dev** [comment]
> Horizon(Inner Core 2.0), with support of C++, Java and JS modding for android. but it's 1.16.201 and closed source. We migrated to armv8(arm64) version of the game from armv7 recently

Hmm.. is there any reason why it's limited to 1.16.201 and why code must stay closed source if Horizon is free software?

**Comment by FrederoxDev** [comment]
Join the OSS gang lmao
