### ISSUE TITLE
Suddenly it is not opening the game.

### ISSUE THREAD

**Issue by ShadowElite117** [FrederoxDev/Amethyst#93]
Let me attach a screenshot:

![image](https://github.com/FrederoxDev/Amethyst/assets/10571638/447065db-f359-4acf-8f31-1ac324c36f77)

**Comment by jLn0n** [comment]
> Let me attach a screenshot:
> 
> ![image](https://private-user-images.githubusercontent.com/10571638/341345403-447065db-f359-4acf-8f31-1ac324c36f77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4OTgxNjEsIm5iZiI6MTcxODg5Nzg2MSwicGF0aCI6Ii8xMDU3MTYzOC8zNDEzNDU0MDMtNDQ3MDY1ZGItZjM1OS00YWNmLThmMzEtMWFjMzI0YzM2Zjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDE1Mzc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzMjcwMTFmOGNlMDZjNmI4NmQ2MTM1MTA5OTM3YWNkM2M4NjAyZTIwODBlMGNmODQxNTZjZjE0M2FmMjJmNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jktArxLW-cj0aKPvrVWIZ_Hs2x4H9J__dUtrXT2LL2Q)

why is it 1.21.3 and not 1.21.0 in your minecraft version?

**Comment by Adrian8115** [comment]
Minecraft has a weird naming schema, that is why 1.21.0.3 is 1.21.3

**Comment by NTT1906** [comment]
> Minecraft has a weird naming schema, that is why 1.21.0.3 is 1.21.3

make a script to read the product/file version rather than the path?

**Comment by NTT1906** [comment]
![image](https://github.com/FrederoxDev/Amethyst/assets/54394881/9d383e95-a2a0-4e56-ab0a-a013486433ca)
oh nvm, weird naming schema

**Comment by FrederoxDev** [comment]
We aren't parsing it from the path. The Microsoft store uses semantic versioning, which only has three segments X.Y.Z where as Minecraft uses 4. Minecraft handles this by combining the last two into one number. Which in this case is "0" and "3" which gets combined into "03"
